# Generated by Django 5.1.7 on 2025-06-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='محصول')),
                ('product_serial_number', models.CharField(max_length=255, unique=True, verbose_name='شماره سریال محصول')),
                ('manufacturing_start_date', models.DateField(verbose_name='تاریخ شروع ساخت')),
                ('manufacturing_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام ساخت')),
                ('test_qc_start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع تست و QC')),
                ('test_qc_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان تست و QC')),
                ('test_approver', models.CharField(blank=True, max_length=255, null=True, verbose_name='تایید کننده تست')),
                ('qc_responsible', models.CharField(blank=True, max_length=255, null=True, verbose_name='مسئول QC')),
                ('product_exit_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خروج محصول')),
                ('exit_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع خروج')),
                ('deliverer', models.CharField(blank=True, max_length=255, null=True, verbose_name='تحویل دهنده')),
                ('receiver', models.CharField(blank=True, max_length=255, null=True, verbose_name='تحویل گیرنده')),
                ('finished_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت تمام شده')),
            ],
            options={
                'verbose_name': 'موجودیت انبار محصولات',
                'verbose_name_plural': 'انبار محصولات',
            },
        ),
        migrations.CreateModel(
            name='QuarantineWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_name', models.CharField(max_length=255, verbose_name='نام قطعه')),
                ('item_code', models.CharField(max_length=255, verbose_name='کد کالا')),
                ('part_number', models.CharField(max_length=255, verbose_name='پارت کالا')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('entry_date', models.DateField(verbose_name='تاریخ ورود')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت (واحد)')),
                ('unit', models.CharField(max_length=50, verbose_name='واحد')),
                ('supplier', models.CharField(max_length=255, verbose_name='تامین کننده')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره سریال')),
                ('status', models.CharField(choices=[('waiting_test', 'در انتظار تست'), ('testing', 'در حال تست'), ('testing_done', 'تست شده'), ('qc_pending', 'در انتظار QC'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('transferred', 'منتقل شده')], default='waiting_test', max_length=50, verbose_name='وضعیت قطعه')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تست')),
                ('test_responsible', models.CharField(blank=True, max_length=255, null=True, verbose_name='مسئول تست')),
                ('test_description', models.TextField(blank=True, null=True, verbose_name='شرح تست')),
                ('qc_date', models.DateField(blank=True, null=True, verbose_name='تاریخ QC')),
                ('qc_responsible', models.CharField(blank=True, max_length=255, null=True, verbose_name='مسئول QC')),
                ('qc_description', models.TextField(blank=True, null=True, verbose_name='شرح QC')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خروج')),
                ('destination', models.CharField(blank=True, choices=[('raw_material', 'انبار مواد اولیه'), ('returned', 'محصول بازگشتی')], max_length=50, null=True, verbose_name='مقصد')),
            ],
            options={
                'verbose_name': 'موجودیت انبار قرنطینه',
                'verbose_name_plural': 'انبار قرنطینه',
            },
        ),
        migrations.CreateModel(
            name='ReturnedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_name', models.CharField(max_length=255, verbose_name='نام قطعه')),
                ('item_code', models.CharField(max_length=255, verbose_name='کد کالا')),
                ('part_number', models.CharField(max_length=255, verbose_name='پارت نامبر')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='تامین کننده')),
                ('return_date', models.DateField(verbose_name='تاریخ بازگشت')),
                ('reason_for_return', models.TextField(verbose_name='دلیل بازگشت')),
                ('responsible_person', models.CharField(max_length=255, verbose_name='مسئول بازگشت')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='واحد')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره سریال')),
            ],
            options={
                'verbose_name': 'محصول بازگشتی',
                'verbose_name_plural': 'محصولات بازگشتی',
            },
        ),
        migrations.CreateModel(
            name='ProductRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material_name', models.CharField(max_length=255, verbose_name='ماده اولیه')),
                ('item_code', models.CharField(max_length=255, verbose_name='کد کالا')),
                ('part_number', models.CharField(max_length=255, verbose_name='پارت نامبر')),
                ('quantity', models.IntegerField(verbose_name='مقدار')),
                ('user_who_used', models.CharField(max_length=255, verbose_name='استفاده کننده')),
                ('raw_material_entry_date', models.DateField(verbose_name='تاریخ ورود ماده اولیه')),
                ('raw_material_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت ماده اولیه')),
                ('unit', models.CharField(max_length=50, verbose_name='واحد')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره سریال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='warehousing.productwarehouse', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ماده اولیه محصول',
                'verbose_name_plural': 'مواد اولیه محصول',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_name', models.CharField(max_length=255, verbose_name='نام قطعه')),
                ('item_code', models.CharField(max_length=255, verbose_name='کد کالا')),
                ('part_number', models.CharField(max_length=255, verbose_name='پارت نامبر')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('entry_date', models.DateField(verbose_name='تاریخ ورود')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('unit', models.CharField(max_length=50, verbose_name='واحد')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره سریال')),
                ('quarantine_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.quarantinewarehouse', verbose_name='ارجاع به قرنطینه')),
            ],
            options={
                'verbose_name': 'موجودیت انبار مواد اولیه',
                'verbose_name_plural': 'انبار مواد اولیه',
            },
        ),
    ]
