# Generated by Django 5.1.7 on 2025-06-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibleForQC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_last_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی مسئول QC')),
            ],
            options={
                'verbose_name': 'مسئول QC',
                'verbose_name_plural': 'مسئول QC',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleForTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_last_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی مسئول تست')),
            ],
            options={
                'verbose_name': 'مسئول تست',
                'verbose_name_plural': 'مسئول تست',
            },
        ),
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='unit',
            field=models.CharField(choices=[('dollar', 'دلار'), ('toman', 'تومان')], max_length=50, verbose_name='واحد'),
        ),
    ]
