# Generated by Django 5.1.7 on 2025-06-15 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0002_responsibleforqc_responsiblefortesting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='qc_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.responsibleforqc', verbose_name='مسئول QC'),
        ),
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='test_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.responsiblefortesting', verbose_name='مسئول تست'),
        ),
    ]
