# Generated by Django 5.1.7 on 2025-06-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0003_alter_quarantinewarehouse_qc_responsible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedproduct',
            name='responsible_person',
        ),
        migrations.AlterField(
            model_name='productrawmaterial',
            name='unit',
            field=models.CharField(choices=[('dollar', 'دلار'), ('toman', 'تومان')], max_length=50, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehouse',
            name='unit',
            field=models.CharField(choices=[('dollar', 'دلار'), ('toman', 'تومان')], max_length=50, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='unit',
            field=models.CharField(blank=True, choices=[('dollar', 'دلار'), ('toman', 'تومان')], max_length=50, null=True, verbose_name='واحد'),
        ),
    ]
