# Generated by Django 5.1.7 on 2025-06-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0004_remove_returnedproduct_responsible_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrawmaterial',
            name='raw_material_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.rawmaterialwarehouse', verbose_name='انتخاب از انبار مواد اولیه'),
        ),
    ]
