# Generated by Django 5.1.7 on 2025-06-29 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0005_productrawmaterial_raw_material_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=255, verbose_name='کد کالا')),
            ],
            options={
                'verbose_name': 'کد کالا',
                'verbose_name_plural': 'کد کالا',
            },
        ),
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_part', models.CharField(max_length=255, verbose_name='پارت کالا')),
            ],
            options={
                'verbose_name': 'پارت کالا',
                'verbose_name_plural': 'پارت کالا',
            },
        ),
        migrations.AlterField(
            model_name='productrawmaterial',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productcode', verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productcode', verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehouse',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productcode', verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productcode', verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='productrawmaterial',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productpart', verbose_name='پارت کالا'),
        ),
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productpart', verbose_name='پارت کالا'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehouse',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productpart', verbose_name='پارت کالا'),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productpart', verbose_name='پارت کالا'),
        ),
    ]
