# Generated by Django 5.1.7 on 2025-06-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0006_productcode_productpart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='status',
            field=models.CharField(choices=[('waiting_test', 'در انتظار تست'), ('testing', 'در حال تست'), ('testing_done', 'تست شده'), ('qc_pending', 'در انتظار QC'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('transferred', 'منتقل شده'), ('used_in_product', 'استفاده شده در محصول')], default='waiting_test', max_length=50, verbose_name='وضعیت قطعه'),
        ),
    ]
