# Generated by Django 5.1.7 on 2025-07-09 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0008_productcode_created_by_productpart_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondryWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='محصول ثانویه')),
                ('product_serial_number', models.CharField(max_length=255, unique=True, verbose_name='شماره سریال محصول ثانویه')),
                ('manufacturing_start_date', models.DateField(verbose_name='تاریخ شروع ساخت')),
                ('manufacturing_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام ساخت')),
                ('test_qc_start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع تست و QC')),
                ('test_qc_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان تست و QC')),
                ('test_approver', models.CharField(blank=True, max_length=255, null=True, verbose_name='تایید کننده تست')),
                ('qc_responsible', models.CharField(blank=True, max_length=255, null=True, verbose_name='مسئول QC')),
                ('product_exit_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خروج محصول')),
                ('exit_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع خروج')),
                ('deliverer', models.CharField(blank=True, max_length=255, null=True, verbose_name='تحویل دهنده')),
                ('receiver', models.CharField(blank=True, max_length=255, null=True, verbose_name='تحویل گیرنده')),
                ('finished_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت تمام شده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'انبار ثانویه',
                'verbose_name_plural': 'انبار ثانویه',
            },
        ),
        migrations.CreateModel(
            name='SecondryWarehouseRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material_name', models.CharField(max_length=255, verbose_name='ماده اولیه')),
                ('quantity', models.IntegerField(verbose_name='مقدار')),
                ('user_who_used', models.CharField(max_length=255, verbose_name='استفاده کننده')),
                ('raw_material_entry_date', models.DateField(verbose_name='تاریخ ورود ماده اولیه')),
                ('raw_material_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت ماده اولیه')),
                ('unit', models.CharField(choices=[('dollar', 'دلار'), ('toman', 'تومان')], max_length=50, verbose_name='واحد')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره سریال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('item_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productcode', verbose_name='کد کالا')),
                ('part_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productpart', verbose_name='پارت کالا')),
                ('raw_material_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.rawmaterialwarehouse', verbose_name='انتخاب از انبار مواد اولیه')),
                ('secondryWarehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='warehousing.secondrywarehouse', verbose_name='محصول انبار ثانویه')),
            ],
            options={
                'verbose_name': 'ماده اولیه انبار ثانویه',
                'verbose_name_plural': 'مواد اولیه انبار ثانویه',
            },
        ),
    ]
