# Generated by Django 5.1.7 on 2025-07-09 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0010_productsecondryproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی تحویل\u200cگیرنده')),
                ('deliverer', models.CharField(max_length=255, verbose_name='تحویل\u200cدهنده')),
                ('delivery_date', models.DateField(verbose_name='تاریخ تحویل')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بازگشت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'تحویل محصول به افراد داخل شرکت',
                'verbose_name_plural': 'تحویل محصولات به افراد داخل شرکت',
            },
        ),
        migrations.CreateModel(
            name='DeliverySecondryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('secondry_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.secondrywarehouse', verbose_name='محصول ثانویه')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondry_products', to='warehousing.productdelivery', verbose_name='تحویل')),
            ],
            options={
                'verbose_name': 'محصول ثانویه تحویلی',
                'verbose_name_plural': 'محصولات ثانویه تحویلی',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.rawmaterialwarehouse', verbose_name='ماده اولیه')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='warehousing.productdelivery', verbose_name='تحویل')),
            ],
            options={
                'verbose_name': 'ماده اولیه تحویلی',
                'verbose_name_plural': 'مواد اولیه تحویلی',
            },
        ),
        migrations.CreateModel(
            name='DeliveryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productwarehouse', verbose_name='محصول')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehousing.productdelivery', verbose_name='تحویل')),
            ],
            options={
                'verbose_name': 'محصول تحویلی',
                'verbose_name_plural': 'محصولات تحویلی',
            },
        ),
    ]
