# Generated by Django 5.1.7 on 2025-07-09 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0011_productdelivery_deliverysecondryproduct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrawmaterial',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliveryrawmaterial',
            name='raw_material',
        ),
        migrations.RemoveField(
            model_name='deliverysecondryproduct',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliverysecondryproduct',
            name='secondry_product',
        ),
        migrations.RemoveField(
            model_name='productdelivery',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='productdelivery',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تحویل دهنده'),
        ),
        migrations.AlterField(
            model_name='productdelivery',
            name='receiver_name',
            field=models.CharField(max_length=255, verbose_name='تحویل گیرنده'),
        ),
        migrations.CreateModel(
            name='ProductDeliveryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='warehousing.productdelivery')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productwarehouse', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDeliveryRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_items', to='warehousing.productdelivery')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.rawmaterialwarehouse', verbose_name='ماده اولیه')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDeliverySecondryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondry_items', to='warehousing.productdelivery')),
                ('secondry_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.secondrywarehouse', verbose_name='محصول ثانویه')),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryProduct',
        ),
        migrations.DeleteModel(
            name='DeliveryRawMaterial',
        ),
        migrations.DeleteModel(
            name='DeliverySecondryProduct',
        ),
    ]
