# Generated by Django 5.1.7 on 2025-07-09 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0012_remove_deliveryrawmaterial_delivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedFromCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی کارفرما')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول برگشتی')),
                ('product_serial_number', models.CharField(max_length=255, verbose_name='شماره سریال محصول')),
                ('return_reason', models.TextField(verbose_name='دلیل برگشت')),
                ('return_date', models.DateField(verbose_name='تاریخ بازگشت')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تحویل گیرنده')),
            ],
            options={
                'verbose_name': 'محصول برگشتی از کارفرما',
                'verbose_name_plural': 'محصولات برگشتی از کارفرما',
            },
        ),
    ]
