# Generated by Django 5.1.7 on 2025-07-09 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0013_returnedfromcustomer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnedproduct',
            options={'verbose_name': 'محصول بازگشتی به فروشنده', 'verbose_name_plural': 'محصولات بازگشتی به فروشنده'},
        ),
        migrations.AddField(
            model_name='returnedfromcustomer',
            name='product_item_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد کالا'),
        ),
        migrations.AddField(
            model_name='returnedfromcustomer',
            name='product_part_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پارت کالا'),
        ),
        migrations.CreateModel(
            name='ExternalProductDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='تحویل گیرنده (خارج از شرکت)')),
                ('delivery_date', models.DateField(verbose_name='تاریخ تحویل')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بازگشت')),
                ('deliverer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تحویل دهنده')),
            ],
            options={
                'verbose_name': 'تحویل محصول به خارج از شرکت',
                'verbose_name_plural': 'تحویل محصولات به خارج از شرکت',
            },
        ),
        migrations.CreateModel(
            name='ExternalProductDeliveryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='warehousing.externalproductdelivery')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productwarehouse', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalProductDeliveryRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_items', to='warehousing.externalproductdelivery')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.rawmaterialwarehouse', verbose_name='ماده اولیه')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalProductDeliverySecondryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondry_items', to='warehousing.externalproductdelivery')),
                ('secondry_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.secondrywarehouse', verbose_name='محصول ثانویه')),
            ],
        ),
    ]
