# Generated by Django 5.1.7 on 2025-07-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0014_alter_returnedproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('serial_number', models.CharField(max_length=255, verbose_name='شماره سریال محصول')),
                ('giver_company', models.CharField(max_length=255, verbose_name='تحویل دهنده (شرکت دیگر)')),
                ('receiver_person', models.CharField(max_length=255, verbose_name='تحویل گیرنده (داخل شرکت)')),
                ('delivery_date', models.DateField(verbose_name='تاریخ تحویل')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بازگرداندن')),
            ],
            options={
                'verbose_name': 'محصول امانتی از شرکت دیگر',
                'verbose_name_plural': 'محصولات امانتی از شرکت\u200cهای دیگر',
            },
        ),
    ]
