# Generated by Django 5.1.7 on 2025-07-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0015_borrowedproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnedproduct',
            options={'verbose_name': 'محصول برگشتی به فروشنده', 'verbose_name_plural': 'محصولات برگشتی به فروشنده'},
        ),
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='status',
            field=models.CharField(choices=[('waiting_test', 'در انتظار تست'), ('testing', 'در حال تست'), ('testing_done', 'تست شده'), ('qc_pending', 'در انتظار QC'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('transferred', 'منتقل شده'), ('used_in_product', 'استفاده شده در محصول'), ('used_in_secondry_warehouse', 'استفاده شده در انبار ثانویه')], default='waiting_test', max_length=50, verbose_name='وضعیت قطعه'),
        ),
    ]
