# Generated by Django 5.1.7 on 2025-07-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0016_alter_returnedproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalproductdeliveryproduct',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='externalproductdeliveryproduct',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ بازگشت'),
        ),
        migrations.AddField(
            model_name='externalproductdeliveryrawmaterial',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='externalproductdeliveryrawmaterial',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ بازگشت'),
        ),
        migrations.AddField(
            model_name='externalproductdeliverysecondryproduct',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='externalproductdeliverysecondryproduct',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ بازگشت'),
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه کاربری تحویل گیرنده'),
        ),
        migrations.AddField(
            model_name='productdeliveryproduct',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='productdeliveryproduct',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ برگشت'),
        ),
        migrations.AddField(
            model_name='productdeliveryrawmaterial',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='productdeliveryrawmaterial',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ برگشت'),
        ),
        migrations.AddField(
            model_name='productdeliverysecondryproduct',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='productdeliverysecondryproduct',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ برگشت'),
        ),
        migrations.AlterField(
            model_name='productdelivery',
            name='receiver_name',
            field=models.CharField(max_length=255, verbose_name='نام و نام خانوادگی تحویل گیرنده'),
        ),
    ]
