# Generated by Django 5.1.7 on 2025-07-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0017_externalproductdeliveryproduct_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondrywarehouserawmaterial',
            options={'verbose_name': 'مواد اولیه انبار ثانویه', 'verbose_name_plural': 'مواد اولیه انبار ثانویه'},
        ),
        migrations.RemoveField(
            model_name='secondrywarehouserawmaterial',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='secondrywarehouserawmaterial',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='secondrywarehouserawmaterial',
            name='raw_material_entry_date',
        ),
        migrations.RemoveField(
            model_name='secondrywarehouserawmaterial',
            name='raw_material_name',
        ),
        migrations.RemoveField(
            model_name='secondrywarehouserawmaterial',
            name='raw_material_price',
        ),
        migrations.RemoveField(
            model_name='secondrywarehouserawmaterial',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='secondrywarehouserawmaterial',
            name='unit',
        ),
        migrations.AlterField(
            model_name='secondrywarehouserawmaterial',
            name='user_who_used',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='استفاده کننده'),
        ),
    ]
