# Generated by Django 5.1.7 on 2025-07-13 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0019_alter_secondrywarehouserawmaterial_raw_material_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondrywarehouserawmaterial',
            name='raw_material_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.rawmaterialwarehouse', verbose_name='انتخاب از انبار مواد اولیه'),
        ),
        migrations.AlterField(
            model_name='secondrywarehouserawmaterial',
            name='secondryWarehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='warehousing.secondrywarehouse', verbose_name='محصول انبار ثانویه'),
        ),
    ]
