# Generated by Django 5.1.7 on 2025-07-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0020_alter_secondrywarehouserawmaterial_raw_material_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondrywarehouserawmaterial',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productcode', verbose_name='کد کالا'),
        ),
        migrations.AddField(
            model_name='secondrywarehouserawmaterial',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousing.productpart', verbose_name='پارت کالا'),
        ),
        migrations.AddField(
            model_name='secondrywarehouserawmaterial',
            name='raw_material_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ورود ماده اولیه'),
        ),
        migrations.AddField(
            model_name='secondrywarehouserawmaterial',
            name='raw_material_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ماده اولیه'),
        ),
        migrations.AddField(
            model_name='secondrywarehouserawmaterial',
            name='raw_material_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت ماده اولیه'),
        ),
        migrations.AddField(
            model_name='secondrywarehouserawmaterial',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره سریال'),
        ),
        migrations.AddField(
            model_name='secondrywarehouserawmaterial',
            name='unit',
            field=models.CharField(blank=True, choices=[('dollar', 'دلار'), ('toman', 'تومان')], max_length=50, null=True, verbose_name='واحد'),
        ),
    ]
